name: cours_ai
description: A Flutter application for AI-assisted course management.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  dio: ^5.4.2
  file_picker: ^8.0.2
  record: ^5.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  pdf: ^3.11.0
  printing: ^5.12.0
  share_plus: ^7.2.1
  go_router: ^14.1.4
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
